### ISSUE TITLE
cannot see paper from arXiv

### ISSUE THREAD

**Issue by ChangerC77** [jmwang0117/AGRNav#1]
I entered arxiv and found that the paper inside is no longer visible. May I ask if it has been published on another platform?

**Comment by jmwang0117** [comment]
Hi,
You can try to access it through this link: https://arxiv.org/abs/2403.11607
Everything is fine when I visit here.

**Comment by ChangerC77** [comment]
thanks, I got it

**Comment by qq0805** [comment]
你好~请问你复现成功了吗 我遇到有些bug不会处理 可否留个联系方式交流一下？

**Comment by ChangerC77** [comment]
> 你好~请问你复现成功了吗 我遇到有些bug不会处理 可否留个联系方式交流一下？

没有，我只是看了paper，后面没有做这个方向，不好意思

**Comment by qq0805** [comment]
Thank u for your reply
Have a nice day！

发自我的iPhone


------------------ Original ------------------
From: Xiangyu Chen ***@***.***&gt;
Date: Fri,Apr 11,2025 9:46 AM
To: jmwang0117/AGRNav ***@***.***&gt;
Cc: qq0805 ***@***.***&gt;, Comment ***@***.***&gt;
Subject: Re: [jmwang0117/AGRNav] cannot see paper from arXiv (Issue #1)



    
你好~请问你复现成功了吗 我遇到有些bug不会处理 可否留个联系方式交流一下？
  
没有，我只是看了paper，后面没有做这个方向，不好意思

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you commented.Message ID: ***@***.***&gt;
  ChangerC77 left a comment (jmwang0117/AGRNav#1)
  
你好~请问你复现成功了吗 我遇到有些bug不会处理 可否留个联系方式交流一下？
  
没有，我只是看了paper，后面没有做这个方向，不好意思
